version: '3.8'
 
services:
  mongodb:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mongodb
    restart: always
    ports:
      - "27018:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=Banco123*
      - MONGO_INITDB_DATABASE=bancodb
    volumes:
      - mongodb_data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
      
  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
 
volumes:
  mongodb_data:
    driver: local
  redis_data:
    driver: local